# Generated by Django 4.1 on 2023-03-09 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis', '0003_rename_match_id_watchedmatch_match_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='team1score',
            new_name='T1SetScore',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='team1name',
            new_name='T1name',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='team2score',
            new_name='T2SetScore',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='team2name',
            new_name='T2name',
        ),
        migrations.AddField(
            model_name='match',
            name='T1Set1',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='T1Set2',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='T1Set3',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='T1Set4',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='T1Set5',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='T2Set1',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='T2Set2',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='T2Set3',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='T2Set4',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='T2Set5',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
