# Generated by Django 4.1 on 2023-03-09 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis', '0004_rename_team1score_match_t1setscore_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='T1Set1',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='match',
            name='T1Set2',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='match',
            name='T1Set3',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='match',
            name='T1Set4',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='match',
            name='T1Set5',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='match',
            name='T1SetScore',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='match',
            name='T2Set1',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='match',
            name='T2Set2',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='match',
            name='T2Set3',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='match',
            name='T2Set4',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='match',
            name='T2Set5',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='match',
            name='T2SetScore',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
