# Generated by Django 4.1 on 2023-03-09 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis', '0006_alter_match_t1set1_alter_match_t1set2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
