# Generated by Django 4.1 on 2023-03-13 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tennis', '0008_remove_match_id_match_match_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='watchedmatch',
            unique_together={('user', 'match')},
        ),
    ]
