# Generated by Django 4.1 on 2023-03-13 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tennis', '0009_alter_watchedmatch_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='watchedmatch',
            unique_together=set(),
        ),
    ]
