# Generated by Django 4.1 on 2023-03-14 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tennis', '0012_watchedmatchcard_delete_watchedmatch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchedmatchcard',
            name='test',
        ),
    ]
