# Generated by Django 4.1 on 2023-04-20 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tennis', '0013_remove_watchedmatchcard_test'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='watchedmatchcard',
            unique_together={('user', 'match')},
        ),
    ]
